site_name: TESLA Documentation
repo_url: http://github.com/cadets/tesla-static-analysis

remote_branch: master
remote_name: deploy

pages:
  - Home: index.md
  - Installation: installation.md
  - Programming:
    - Tutorial: programming.md
    - "Macro Reference": macros.md
    - "Static Analysis": static.md

markdown_extensions:
  - smarty
